[package]
name = "notaudio"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
rodio = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"